### ISSUE TITLE
Migration between Different Database?

### ISSUE THREAD

**Issue by prashant7july** [awapps/mongration#31]
I want to migration from mysql to mongodb, Is that possible?

**Comment by wmartins** [comment]
Hey @prashant7july, I don't know if you got it right, but mongration is not a "migration between databases" tool it is a "migration for MongoDB databases". Also, MongoDB and MySQL have lots of differences. For example, MongoDB doesn't have some concepts that MySQL does (i.e: tables). So, personally saying, I think that it would be really hard to do something like that perfectly (but it is a really interesting problem to solve).

Therefore, mongration is a tool that will help you to make changes to your running mongodb databases. For example, in one day you have 3 records in your database, and mongration will have some modifications (called migrations) that may alter those 3 records (adding data to them, removing, etc.). So, you run a command and mongration will say if the migrations ran successfully, how many migrations ran and etc.

I found this StackOverflow thread interesting to your case: http://stackoverflow.com/questions/6251548/converting-database-from-mysql-to-mongodb.

And this: http://linuxpitstop.com/migrate-mysql-to-mongodb-using-mongify-utility-linux/.

Do you mind if I close this issue?
