### ISSUE TITLE
BUG during validation

### ISSUE THREAD

**Issue by viktornord** [awapps/mongration#47]
This module always throws an error during validation saying that migration was performed in a reverse order.
I've check the validation function and noticed that it iterates over docs and considers each doc as a migration step checking it's `order` & `id` prop which leads to error.
https://github.com/awapps/mongration/blob/e45ed658b90fa6dbd4dffb374278ee15bd2602ab/src/migration.js#L33

**Comment by wmartins** [comment]
Hey @viktornord, can you provide more details to that? Things like your file structure and how can you reproduce that can help us help you. :)

In what case the error happens? We tested `mongration` a lot some time ago, adding new migrations and etc and it never occurred (not that we've noticed).

Thanks!

**Comment by viktornord** [comment]
Hi, @wmartins 
I've noticed there were some commits since I opened this issue. Maybe I did something.
Anyway I tried it again and could not reproduce the issue. Guess it could be closed.
