### ISSUE TITLE
yarn audit throws errors due to an outdated lodash used by master-table.js

### ISSUE THREAD

**Issue by zelongc** [awapps/mongration#50]
Hi there,

I am really appreciated for your awesome work.

Is there any chance to use another package instead of table-master.js as the table-master.js is using a vulnerably dependency ```"lodash": "^3.10.1"```

Thanks

**Comment by Sytten** [comment]
Same here. Could you fix it @eberhara or @wmartins. Thanks!

**Comment by wmartins** [comment]
Hey @zelongc and @Sytten, just published out a new version (`v1.0.1`) replacing the `console.table` dependency. The audit error should be fixed now. :)

Let me know if you still have problems with that.

**Comment by zelongc** [comment]
@wmartins Thank you very much!
